# Advent of Code 2021

In [1]:
import matplotlib.pyplot as plt
import numpy as np

## Day 4: Giant Squid

### Part 1:

You're already almost 1.5km (almost a mile) below the surface of the ocean, already so deep that you can't see any sunlight. What you **can** see, however, is a giant squid that has attached itself to the outside of your submarine.

Maybe it wants to play bingo?

Bingo is played on a set of boards each consisting of a 5x5 grid of numbers. Numbers are chosen at random, and the chosen number is **marked** on all boards on which it appears. (Numbers may not appear on all boards.) If all numbers in any row or any column of a board are marked, that board **wins**. (Diagonals don't count.)

The submarine has a **bingo subsystem** to help passengers (currently, you and the giant squid) pass the time. It automatically generates a random order in which to draw numbers and a random set of boards (your puzzle input). For example:

```
7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1

22 13 17 11  0
 8  2 23  4 24
21  9 14 16  7
 6 10  3 18  5
 1 12 20 15 19

 3 15  0  2 22
 9 18 13 17  5
19  8  7 25 23
20 11 10 24  4
14 21 16 12  6

14 21 17 24  4
10 16 15  9 19
18  8 23 26 20
22 11 13  6  5
 2  0 12  3  7
```

After the first five numbers are drawn (`7`, `4`, `9`, `5`, and `11`), there are no winners, but the boards are marked as follows (shown here adjacent to each other to save space):

```
22 13 17 11  0         3 15  0  2 22        14 21 17 24  4
 8  2 23  4 24         9 18 13 17  5        10 16 15  9 19
21  9 14 16  7        19  8  7 25 23        18  8 23 26 20
 6 10  3 18  5        20 11 10 24  4        22 11 13  6  5
 1 12 20 15 19        14 21 16 12  6         2  0 12  3  7
```

After the next six numbers are drawn (`17`, `23`, `2`, `0`, `14`, and `21`), there are still no winners:

```
22 13 17 11  0         3 15  0  2 22        14 21 17 24  4
 8  2 23  4 24         9 18 13 17  5        10 16 15  9 19
21  9 14 16  7        19  8  7 25 23        18  8 23 26 20
 6 10  3 18  5        20 11 10 24  4        22 11 13  6  5
 1 12 20 15 19        14 21 16 12  6         2  0 12  3  7
```

Finally, `24` is drawn:

```
22 13 17 11  0         3 15  0  2 22        14 21 17 24  4
 8  2 23  4 24         9 18 13 17  5        10 16 15  9 19
21  9 14 16  7        19  8  7 25 23        18  8 23 26 20
 6 10  3 18  5        20 11 10 24  4        22 11 13  6  5
 1 12 20 15 19        14 21 16 12  6         2  0 12  3  7
```

At this point, the third board **wins** because it has at least one complete row or column of marked numbers (in this case, the entire top row is marked: `14 21 17 24  4`).

The **score** of the winning board can now be calculated. Start by finding the **sum of all unmarked numbers** on that board; in this case, the sum is `188`. Then, multiply that sum by **the number that was just called** when the board won, `24`, to get the final score, `188 * 24 = **4512`.

To guarantee victory against the giant squid, figure out which board will win first. **What will your final score be if you choose that board?**

In [49]:
with open("./private/2021/04.in") as f:
	draws = np.array(list(map(int, f.readline().strip().split(','))))
	card_strings = f.read().split('\n\n')
	cards = np.array([[list(map(int, row.split())) for row in card.strip().split('\n')] for card in card_strings])
len(draws), cards.shape

(100, (100, 5, 5))

In [54]:
marked_cards = cards.copy()
for draw in draws:
	indices = np.where(marked_cards == draw)
	marked_cards[indices] = -1
	row_sums = np.sum(marked_cards, axis=2)
	col_sums = np.sum(marked_cards, axis=1)

	row_win = np.argwhere(row_sums == -5)
	if len(row_win):
		winning_card = row_win[0][0]
		break
	col_win = np.argwhere(col_sums == -5)
	if len(row_win) or len(col_win):
		winning_card = col_win[0][0]
		break
print("Winning card:", winning_card)
print("Last drawn number:", draw)
print(marked_cards[winning_card])

Winning card: 40
Last drawn number: 96
[[-1 34 55 90 64]
 [-1 -1 94 48 91]
 [-1 45 -1 58 63]
 [-1 20 43 73 -1]
 [-1 52 49  8 24]]


In [60]:
card = marked_cards[winning_card].copy()
score = draw * np.sum(card[np.where(card >= 0)])
score

87456

### Part 2:

On the other hand, it might be wise to try a different strategy: let the giant squid win.

You aren't sure how many bingo boards a giant squid could play at once, so rather than waste time counting its arms, the safe thing to do is to **figure out which board will win last** and choose that one. That way, no matter which boards it picks, it will win for sure.

In the above example, the second board is the last to win, which happens after `13` is eventually called and its middle column is completely marked. If you were to keep playing until this point, the second board would have a sum of unmarked numbers equal to `148` for a final score of `148 * 13 = **1924`.

Figure out which board will win last. **Once it wins, what would its final score be?**

In [77]:
marked_cards = cards.copy()
last_winning_card = None
for draw in draws:
	indices = np.where(marked_cards == draw)
	marked_cards[indices] = -1
	row_sums = np.sum(marked_cards, axis=2)
	col_sums = np.sum(marked_cards, axis=1)

	row_win = np.where(row_sums == -5)[0]
	col_win = np.where(col_sums == -5)[0]
	winning_cards = np.concatenate((row_win, col_win))
	if len(winning_cards):
		last_winning_card = marked_cards[winning_cards[0]]
		marked_cards = np.delete(marked_cards, winning_cards, axis=0)

last_winning_card

array([[46, -1, -1, 86, -1],
       [-1, -1, -1, -1, 53],
       [-1, -1, -1, -1, -1],
       [-1, 95, -1, -1, -1],
       [28, -1, 91, -1, -1]])

In [76]:
card = last_winning_card
score = draw * np.sum(card[np.where(card >= 0)])
score

15561