# Advent of Code 2021

In [1]:
from collections import defaultdict
import matplotlib.pyplot as plt
import numpy as np
import queue

import common

In [242]:

dots = []
folds = []
with open("./private/2021/13.in") as f:
	for line in f:
		if line == "\n":
			break
		dots.append(common.csv(line))
	for line in f:
		axis, value = line.strip().split('=')
		folds.append((axis[-1] == 'y', int(value)))
dots = np.array(dots)
folds = np.array(folds)

In [243]:
x, y = dots.T
grid = np.zeros((np.max(dots[:,1]+1), np.max(dots[:,0]+1)))
grid[y,x] = np.inf

In [244]:
for (axis, dist) in folds:
	if axis == 1: # flip that shit
		grid = grid.T

	left = grid[:,:dist]
	right = grid[:,dist+1:][:,::-1]

	offset = right.shape[1] - left.shape[1]
	left = np.pad(left, ((0, 0), (max(offset, 0), 0)))
	right = np.pad(right, ((0, 0), (max(-offset, 0), 0)))
	grid = left + right

	if axis == 1: # now flip that shit back
		grid = grid.T

In [245]:
for i in range(grid.shape[0]):
	for j in range(grid.shape[1]):
		print('#' if grid[i][j] == np.inf else ' ', end="")
		if np.all(grid[:,j] == 0):
			print('     ', end="")
	print()

####      #  #        ##      #  #       ##       ####      #  #      ###       
   #      #  #         #      #  #      #  #      #         #  #      #  #      
  #       #  #         #      #  #      #  #      ###       ####      #  #      
 #        #  #         #      #  #      ####      #         #  #      ###       
#         #  #      #  #      #  #      #  #      #         #  #      #         
####       ##        ##        ##       #  #      #         #  #      #         


In [181]:
np.sum()

array([[1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
        1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
        0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0]])

In [180]:
grid

array([[inf, inf, inf, inf,  0., inf,  0.,  0., inf,  0.,  0.,  0., inf,
        inf,  0., inf,  0.,  0., inf,  0.,  0., inf, inf,  0.,  0., inf,
        inf, inf, inf,  0., inf,  0.,  0., inf,  0., inf, inf, inf,  0.,
         0.],
       [ 0.,  0.,  0., inf,  0., inf,  0.,  0., inf,  0.,  0.,  0.,  0.,
        inf,  0., inf,  0.,  0., inf,  0., inf,  0.,  0., inf,  0., inf,
         0.,  0.,  0.,  0., inf,  0.,  0., inf,  0., inf,  0.,  0., inf,
         0.],
       [ 0.,  0., inf,  0.,  0., inf,  0.,  0., inf,  0.,  0.,  0.,  0.,
        inf,  0., inf,  0.,  0., inf,  0., inf,  0.,  0., inf,  0., inf,
        inf, inf,  0.,  0., inf, inf, inf, inf,  0., inf,  0.,  0., inf,
         0.],
       [ 0., inf,  0.,  0.,  0., inf,  0.,  0., inf,  0.,  0.,  0.,  0.,
        inf,  0., inf,  0.,  0., inf,  0., inf, inf, inf, inf,  0., inf,
         0.,  0.,  0.,  0., inf,  0.,  0., inf,  0., inf, inf, inf,  0.,
         0.],
       [inf,  0.,  0.,  0.,  0., inf,  0.,  0., inf,  0., inf,  0., 

In [160]:
np.sum(grid == np.inf)

737

In [77]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

In [79]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [161]:
grid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])