In [1]:
import sys
sys.path.append("../../common")
from aoc import *


import datetime
from itertools import count, combinations
import matplotlib.pyplot as plt
import numpy as np
import re
import shapely
from tqdm import tqdm
from IPython.display import clear_output

In [272]:
with open("./puzzle_inputs/06.txt") as f:
    points = arr([tuple(map(int, line.split(', '))) for line in f])

In [273]:
# points = np.array([
#     [1, 1],
#     [1, 6],
#     [8, 3],
#     [3, 4],
#     [5, 5],
#     [8, 9],
# ])

In [274]:
len(points)

50

In [275]:
point = points[1]
grid = np.empty((np.max(points) + 1, np.max(points) + 1), dtype=int)
x, y = np.meshgrid(np.arange(grid.shape[0]), np.arange(grid.shape[1]))
others = np.vstack((y.flatten(), x.flatten())).T
grid[y.flatten(),x.flatten()] = np.sum(np.abs(others - point), axis=1)
grid

array([[461, 460, 459, ..., 150, 151, 152],
       [460, 459, 458, ..., 149, 150, 151],
       [459, 458, 457, ..., 148, 149, 150],
       ...,
       [560, 559, 558, ..., 249, 250, 251],
       [561, 560, 559, ..., 250, 251, 252],
       [562, 561, 560, ..., 251, 252, 253]])

In [276]:
distance_grids = []
for i, point in enumerate(points):
    grid = np.empty((np.max(points) + 1, np.max(points) + 1), dtype=int)
    x, y = np.meshgrid(np.arange(grid.shape[0]), np.arange(grid.shape[1]))
    others = np.vstack((y.flatten(), x.flatten())).T
    grid[y.flatten(),x.flatten()] = np.sum(np.abs(others - point), axis=1)
    distance_grids.append(grid)
distance_grids = np.array(distance_grids)

In [277]:
smallest = np.min(distance_grids, axis=0)
smallest

array([[164, 163, 162, ...,  82,  81,  80],
       [163, 162, 161, ...,  81,  80,  79],
       [162, 161, 160, ...,  80,  79,  78],
       ...,
       [ 79,  78,  77, ...,  65,  66,  67],
       [ 80,  79,  78, ...,  66,  67,  68],
       [ 81,  80,  79, ...,  67,  68,  69]])

In [278]:
1 - (np.sum(distance_grids == smallest, axis=0) > 1).astype(int)

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [279]:
mask = 1 - (np.sum(distance_grids == smallest, axis=0) > 1).astype(int)
mask

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [280]:
areas = (1 + np.argmin(distance_grids, axis=0)) * mask - 1

In [281]:
np.argmin(distance_grids, axis=0)

array([[42, 42, 42, ..., 23, 23, 23],
       [42, 42, 42, ..., 23, 23, 23],
       [42, 42, 42, ..., 23, 23, 23],
       ...,
       [12, 12, 12, ..., 44, 44, 44],
       [12, 12, 12, ..., 44, 44, 44],
       [12, 12, 12, ..., 44, 44, 44]])

In [282]:
areas

array([[42, 42, 42, ..., 23, 23, 23],
       [42, 42, 42, ..., 23, 23, 23],
       [42, 42, 42, ..., 23, 23, 23],
       ...,
       [12, 12, 12, ..., 44, 44, 44],
       [12, 12, 12, ..., 44, 44, 44],
       [12, 12, 12, ..., 44, 44, 44]])

In [284]:
valid_ids = set(range(len(points))) - set(areas[0]) - set(areas[-1]) - set(areas[:,0]) - set(areas[:,-1])
# valid_ids

In [285]:
_, counts = np.unique(areas, return_counts=True)
np.max(counts[arr(list(valid_ids)) + 1])

3604

In [286]:
np.sum(distance_grids.sum(axis=0) < 10000)

46563